# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_todos', '0008_remove_list_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='meteor_collection',
            field=models.CharField(default=b'lists', max_length=20),
        ),
        migrations.AddField(
            model_name='todos',
            name='meteor_collection',
            field=models.CharField(default=b'todos', max_length=20),
        ),
    ]
